name: mhs-ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-mhs-filepath:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # windows doesn't quite work yet
        os: [ubuntu-latest, macOS-15-intel, macOS-latest]
        mhs: [0.15.0.0]

    steps:

    - name: checkout mhs repo
      uses: actions/checkout@v4
      with:
        repository: augustss/MicroHs
        ref: v${{ matrix.mhs }}
        path: mhs

    - name: make and install mhs
      if: runner.os == 'Windows'
      run: |
        cd mhs
        nmake /F Makefile.windows

    - name: make and install mhs
      if: runner.os != 'Windows'
      run: |
        cd mhs
        make minstall

    - name: install packages
      run: |
        cd mhs
        export PATH="$HOME/.mcabal/bin:$PATH"
        make -f Makefile.packages
      shell: bash

    - name: checkout filepath repo
      uses: actions/checkout@v4
      with:
        path: filepath

    - name: compile and install filepath package
      run: |
        export PATH="$HOME/.mcabal/bin:$PATH"
        cd filepath
        mcabal -r install

    - name: cleanup
      run: |
        rm -rf "$HOME/.mcabal"

